name: mercure-radiomics

channels:
- conda-forge

dependencies:
- python==3.11
- numpy
- SimpleITK
- PyWavelets
- pykwalify
- six
- pydicom
- anaconda::gcc_linux-64
- pip
- pip:
  - numpy
  - mirp
  - highdicom
  - rt-utils
  - pyradiomics
